version: "3.7"
services:

  mongo:
    image: mongo:4
    networks:
      - acheronet
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "caronte"
      MONGO_INITDB_ROOT_PASSWORD: "caronte"

  caronte:
    build:
      context: .
      dockerfile: Dockerfile.testing
    image: caronte
    ports:
      - "6666:6666"
    depends_on:
      - mongo
    networks:
      - acheronet
    command: "./scripts/travis_tests.sh"
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      DB_USERNAME: caronte
      DB_PASSWORD: caronte

networks:
  acheronet:
