version: "3.7"
services:

  mongo:
    image: mongo:4
    networks:
      - acheronet
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: SET_YOUR_CREDENTIAL
      MONGO_INITDB_ROOT_PASSWORD: SET_YOUR_CREDENTIAL

  caronte:
    image: eciavatta/caronte:latest
    ports:
      - "3333:3333"
    depends_on:
      - mongo
    networks:
      - acheronet
    command: ./caronte -mongo-host mongo -mongo-port 27017 -dbUsername SET_YOUR_CREDENTIAL -dbPassword SET_YOUR_CREDENTIAL -assembly_memuse_log

networks:
  acheronet:
